/**
 * Battle Creation Scheduler
 * 
 * This module handles:
 * 1. Taking reconciled fixtures as input
 * 2. Creating battles for upcoming fixtures (within N days, default 3)
 * 3. Respecting manual admin overrides (don't overwrite manually-created battles)
 * 4. Idempotency (can be run repeatedly without duplicating battles)
 * 
 * Warning flags:
 * - manuallyCreated: battle was created by admin, don't auto-modify
 * - autoGenerated: battle was auto-created from fixture, can be updated
 */

import { Fixture } from "./fixtureSourceAdapters";

/**
 * Extended battle type with metadata for scheduling
 */
export interface ScheduledBattle {
  slug: string;
  title: string;
  description: string;
  homeSlug: string;
  awaySlug: string;
  kickoffTime: string;
  competition: string;
  
  // Metadata for reconciliation with fixtures
  fixtureId?: string;
  manuallyCreated: boolean; // if true, don't overwrite
  autoGenerated: boolean; // if true, can update from fixture
  createdAt: string;
  updatedAt: string;
}

/**
 * Configuration for battle scheduler
 */
export interface SchedulerConfig {
  /**
   * Days ahead to look for fixtures (default: 3)
   */
  daysAhead: number;
}

const DEFAULT_CONFIG: SchedulerConfig = {
  daysAhead: 3,
};

/**
 * Generates a slug for a battle from two club slugs and timestamp
 * Format: "{home-slug}-vs-{away-slug}"
 * This is deterministic so the same matchup always gets the same slug
 */
export function generateBattleSlug(homeSlug: string, awaySlug: string): string {
  return `${homeSlug}-vs-${awaySlug}`;
}

/**
 * Generates a title for a battle
 */
export function generateBattleTitle(homeDisplayName: string, awayDisplayName: string): string {
  return `${homeDisplayName} vs ${awayDisplayName} Chant Battle`;
}

/**
 * Generates a description for a battle
 */
export function generateBattleDescription(
  homeDisplayName: string,
  awayDisplayName: string,
  competition: string,
): string {
  return `${homeDisplayName} takes on ${awayDisplayName} in the ${competition}. Which team's supporters will dominate the chants?`;
}

/**
 * Creates or updates battles from reconciled fixtures
 * 
 * Algorithm:
 * 1. Filter fixtures to only those within daysAhead
 * 2. For each fixture:
 *    a. Check if battle already exists (by slug)
 *    b. If exists and manually created: skip
 *    c. If exists and auto-generated: update
 *    d. If doesn't exist: create new
 * 
 * Args:
 * - fixtures: reconciled fixture list
 * - existingBattles: current battles in system
 * - clubRegistry: map of slug -> displayName
 * - config: scheduler configuration
 */
export function createBattlesFromFixtures(
  fixtures: Fixture[],
  existingBattles: Map<string, ScheduledBattle>,
  clubRegistry: Map<string, string>, // slug -> displayName
  config: Partial<SchedulerConfig> = {},
): { created: ScheduledBattle[]; updated: ScheduledBattle[]; skipped: string[] } {
  const mergedConfig = { ...DEFAULT_CONFIG, ...config };
  
  const now = new Date();
  const cutoffTime = new Date(now.getTime() + mergedConfig.daysAhead * 24 * 60 * 60 * 1000);

  const created: ScheduledBattle[] = [];
  const updated: ScheduledBattle[] = [];
  const skipped: string[] = [];

  for (const fixture of fixtures) {
    const fixtureTime = new Date(fixture.kickoffTime);
    
    // Only process fixtures within the time window
    if (fixtureTime > cutoffTime) {
      console.log(
        `[Scheduler] Skipping fixture ${fixture.homeSlug} vs ${fixture.awaySlug}: too far in future`,
      );
      continue;
    }

    // Get display names
    const homeDisplayName = clubRegistry.get(fixture.homeSlug);
    const awayDisplayName = clubRegistry.get(fixture.awaySlug);

    if (!homeDisplayName || !awayDisplayName) {
      console.warn(
        `[Scheduler] Skipping fixture: unknown club slug (${fixture.homeSlug} or ${fixture.awaySlug})`,
      );
      continue;
    }

    const battleSlug = generateBattleSlug(fixture.homeSlug, fixture.awaySlug);
    const existingBattle = existingBattles.get(battleSlug);

    if (existingBattle) {
      // Battle exists
      if (existingBattle.manuallyCreated) {
        // Don't overwrite manually-created battles
        console.log(`[Scheduler] Skipping ${battleSlug}: manually created`);
        skipped.push(battleSlug);
      } else if (existingBattle.autoGenerated) {
        // Update auto-generated battles
        const updated_battle: ScheduledBattle = {
          ...existingBattle,
          description: generateBattleDescription(homeDisplayName, awayDisplayName, fixture.competition),
          kickoffTime: fixture.kickoffTime,
          competition: fixture.competition,
          fixtureId: fixture.externalId,
          updatedAt: new Date().toISOString(),
        };
        updated.push(updated_battle);
        existingBattles.set(battleSlug, updated_battle);
        console.log(`[Scheduler] Updated ${battleSlug}`);
      }
    } else {
      // Create new battle
      const newBattle: ScheduledBattle = {
        slug: battleSlug,
        title: generateBattleTitle(homeDisplayName, awayDisplayName),
        description: generateBattleDescription(homeDisplayName, awayDisplayName, fixture.competition),
        homeSlug: fixture.homeSlug,
        awaySlug: fixture.awaySlug,
        kickoffTime: fixture.kickoffTime,
        competition: fixture.competition,
        fixtureId: fixture.externalId,
        manuallyCreated: false,
        autoGenerated: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      created.push(newBattle);
      existingBattles.set(battleSlug, newBattle);
      console.log(`[Scheduler] Created ${battleSlug}`);
    }
  }

  return { created, updated, skipped };
}

/**
 * Helper: Convert a battle to scheduled battle metadata
 */
export function markBattleAsManuallyCreated(battle: ScheduledBattle): ScheduledBattle {
  return {
    ...battle,
    manuallyCreated: true,
    autoGenerated: false,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Helper: Mark battle for auto-management again
 */
export function markBattleAsAutoGenerated(battle: ScheduledBattle): ScheduledBattle {
  return {
    ...battle,
    manuallyCreated: false,
    autoGenerated: true,
    updatedAt: new Date().toISOString(),
  };
}
