// scripts/clubs.ts

export const premierLeagueClubs = [
  "Arsenal",
  "Aston Villa",
  "AFC Bournemouth",
  "Brentford",
  "Brighton & Hove Albion",
  "Burnley",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Leeds United",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Newcastle United",
  "Nottingham Forest",
  "Sunderland",
  "Tottenham Hotspur",
  "West Ham United",
  "Wolverhampton Wanderers",
];

export const championshipClubs = [
  "Birmingham City",
  "Blackburn Rovers",
  "Bristol City",
  "Charlton Athletic",
  "Coventry City",
  "Derby County",
  "Hull City",
  "Ipswich Town",
  "Leicester City",
  "Middlesbrough",
  "Millwall",
  "Norwich City",
  "Oxford United",
  "Preston North End",
  "Queens Park Rangers",
  "Sheffield United",
  "Sheffield Wednesday",
  "Southampton",
  "Stoke City",
  "Sunderland", // NOTE: if Sunderland is in PL list above, remove from here (don’t duplicate)
  "Swansea City",
  "Watford",
  "West Bromwich Albion",
  "Wrexham",
];